TournamentScheduler/Models/Tournament.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace TournamentScheduler.Models
{
    [Table("Tournament")]
    public class Tournament
    {
        [Key]
        public int TournamentID { get; set; }

        [Required]
        [Display(Name = "Tournament Name")]
        public string TournamentName { get; set; }

        [ScaffoldColumn(false)]
        public string TournamentOwnerID { get; set; }

        [ScaffoldColumn(false)]
        [DefaultValue(false)]
        public bool TournamentStarted { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        public virtual ICollection<Team> Teams { get; set; }

        public virtual ICollection<RRFixture> RRFixtures { get; set; }
    }
}

TournamentScheduler/Controllers/TeamController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TournamentScheduler.Models;

namespace TournamentScheduler.Controllers
{
    public class TeamController : Controller
    {
        private TournamentSchedulerContext db = new TournamentSchedulerContext();

        //// GET: Team
        //public ActionResult Index()
        //{
        //    return View(db.Teams.ToList());
        //}

        //// GET: Team/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Team team = db.Teams.Find(id);
        //    if (team == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(team);
        //}

        // GET: Team/Create
        [Authorize]
        public ActionResult Create(int? TeamTournamentID)
        {
            Tournament MyTournament = db.Tournaments.Find(TeamTournamentID);

            string TournamentUserID = MyTournament.TournamentOwnerID;
            string currentUserID = User.Identity.GetUserId();
            if (TournamentUserID == currentUserID)
            {
                Team team = new Team();
                team.TournamentID = (int)TeamTournamentID;
                return View(team);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // POST: Team/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TeamID,TeamName")] Team team, int TeamTournamentID)
        {
            if (ModelState.IsValid)
            {
                team.TournamentID = TeamTournamentID;
                db.Teams.Add(team);
                db.SaveChanges();
                return RedirectToAction("Details", "Tournament", new { id = TeamTournamentID } );
            }

            return View(team);
        }

        //// GET: Team/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Team team = db.Teams.Find(id);
        //    if (team == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(team);
        //}

        //// POST: Team/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "TeamID,TeamName")] Team team)
        //{
        //    if (ModelState.IsValid)
        //    {

        //        db.Entry(team).State = EntityState.Modified;
        //        // Set a default for testing
        //        team.TournamentID = 1;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(team);
        //}

        // GET: Team/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = db.Teams.Find(id);
            int TeamTournamentID = team.TournamentID;
            Tournament tournament = db.Tournaments.Find(TeamTournamentID);
            string TournamentUserID = tournament.TournamentOwnerID;
            string currentUserID = User.Identity.GetUserId();
            
            if (team == null)
            {
                return HttpNotFound();
            }
            if (TournamentUserID == currentUserID)
            {
                return View(team);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // POST: Team/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Team team = db.Teams.Find(id);
            int TeamTournamentID = team.TournamentID;
            db.Teams.Remove(team);
            db.SaveChanges();
            return RedirectToAction("Details", "Tournament", new { id = TeamTournamentID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TournamentScheduler/Controllers/TournamentController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TournamentScheduler.Models;

namespace TournamentScheduler.Controllers
{
    public class TournamentController : Controller
    {
        private TournamentSchedulerContext db = new TournamentSchedulerContext();

        // GET: Tournament
        [Authorize]
        public ActionResult Index()
        {
            string currentUserID = User.Identity.GetUserId();
            var tournaments = db.Tournaments.Where(e => e.TournamentOwnerID == currentUserID);
            return View(tournaments.ToList());
        }

        // GET: Tournament/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            string currentUserID = User.Identity.GetUserId();
            if (tournament.TournamentOwnerID == currentUserID)
            {
                return View(tournament);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // GET: Tournament/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tournament/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TournamentID,TournamentName,TournamentOwnerID,StartDate")] Tournament tournament)
        {
            if (ModelState.IsValid)
            {
                tournament.TournamentOwnerID = User.Identity.GetUserId();
                db.Tournaments.Add(tournament);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tournament);
        }


        //GET: Round Robin
        [Authorize]
        public ActionResult RoundRobin(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tournament tournament = db.Tournaments.Find(id);
            if (tournament == null)
            {
                return HttpNotFound();
            }
            string currentUserID = User.Identity.GetUserId();
            if (tournament.TournamentOwnerID == currentUserID)
            {
                if (tournament.TournamentStarted == false)
                {
                    //Get team names associated to the tournament
                    //Generate round robin fixtures
                    //Add fixtures to fixture table

                    //Full List of Team Names
                    List<string> TeamNameList = new List<string>();

                    foreach (var myTeam in tournament.Teams)
                    {
                        string AddThis = myTeam.TeamName;
                        TeamNameList.Add(myTeam.TeamName);
                    }

                    //Length of list
                    int HowManyTeams = TeamNameList.Count();

                    //Find if # of teams is even
                    bool TeamIsEven;
                    if (HowManyTeams % 2 == 0)
                    {
                        TeamIsEven = true;
                    }
                    else
                    {
                        TeamIsEven = false;
                    }

                    //midway point of list
                    int mid = HowManyTeams / 2;

                    //The two lists needed to generate fixtures
                    List<string> RRList1 = TeamNameList.Take(mid).ToList();
                    List<string> RRList2 = TeamNameList.Skip(mid).ToList();

                    //Fill in list so they are the same length, null will be a bye
                    if (TeamIsEven == false)
                    {
                        RRList1.Add(null);
                    }

                    //If odd, mid would be 2, if even it would be 3 in this example
                    int LastListIndex;
                    if (TeamIsEven == true)
                    {
                        //mid is 3, index needs to go to 2
                        LastListIndex = mid - 1;
                    }
                    else
                    {
                        //mid is 2, index can =
                        LastListIndex = mid;
                    }

                    //Reverse list to make fixture generating easier
                    //(First team will play the last in the first game)
                    RRList2.Reverse();

                    int count = 1;
                    int count2 = 0;
                    var MyFixture = new RRFixture();
                    MyFixture.TournamentID = tournament.TournamentID;

                    int newHowManyTeams;
                    if (HowManyTeams % 2 == 1)
                    {
                        newHowManyTeams = HowManyTeams + 1;
                    }
                    else
                    {
                        newHowManyTeams = HowManyTeams;
                    }

                    //Rounds
                    while (count < newHowManyTeams)
                    {
                        //Set round number
                        MyFixture.RoundNumber = count;
                        //Escape Case
                        count += 1;
                        

                        //Matches per round
                        while (count2 <= LastListIndex)
                        {
                            //Add the matching index in each list with each other
                            MyFixture.Team1Name = RRList1[count2];
                            MyFixture.Team2Name = RRList2[count2];

                            //add the fixture with the tournamentid, roundnumber, team1name and team2name

                            db.RRFixtures.Add(MyFixture);
                            db.SaveChanges();

                            //Escape case
                            count2 += 1;
                        }
                        //Reset Match loop counter
                        count2 = 0;

                        // After each round alter the lists so that every team plays each other
                        // For round robin, keep the first team in the same position and rotate
                        // the rest around till they have all played each other

                        //LastListIndex = 2

                        //-----------------------ROUND 1------------------------
                        //RRList1 = [DMU, Cabbage Family, *NULL*]
                        //RRList2 = [Man City, Liverpool, Man U]

                        RRList1.Insert(1, RRList2[0]);

                        //RRList1 = [DMU, Man City, Cabbage Family, *NULL*]
                        //RRList2 = [Man City, Liverpool, Man U]

                        RRList2.RemoveAt(0);

                        //RRList1 = [DMU, Man City, Cabbage Family, *NULL*]
                        //RRList2 = [Liverpool, Man U]

                        RRList2.Add(RRList1[LastListIndex + 1]);

                        //RRList1 = [DMU, Man City, Cabbage Family, *NULL*]
                        //RRList2 = [Liverpool, Man U, *NULL*]

                        RRList1.RemoveAt(LastListIndex + 1);

                        //RRList1 = [DMU, Man City, Cabbage Family]
                        //RRList2 = [Liverpool, Man U, *NULL*]

                        //-----------------------ROUND 2------------------------
                        //RRList1 = [DMU, Man City, Cabbage Family]
                        //RRList2 = [Liverpool, Man U, *NULL*]

                        //-----------------------ROUND 3------------------------
                        //RRList1 = [DMU, Liverpool, Man City]
                        //RRList2 = [Man U, *NULL*, Cabbage Family]

                        //-----------------------ROUND 4------------------------
                        //RRList1 = [DMU, Man U, Liverpool]
                        //RRList2 = [*NULL*, Cabbage Family, Man City]

                        //-----------------------ROUND 5------------------------
                        //RRList1 = [DMU, *NULL*, Man U]
                        //RRList2 = [Cabbage Family, Man City, Liverpool]

                    }
                    tournament.TournamentStarted = true;
                    db.SaveChanges();
                }
                return View(tournament);


            }
            else
            {
                return HttpNotFound();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TournamentScheduler/Views/Tournament/Create.cshtml
@model TournamentScheduler.Models.Tournament

@{
    ViewBag.Title = "Create Tournament";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Tournament</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TournamentName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TournamentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TournamentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Start Date</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("View all Tournaments", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TournamentScheduler/Views/Tournament/Details.cshtml
@model TournamentScheduler.Models.Tournament

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TournamentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TournamentName)
        </dd>

        <dt>
            Start Date
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            Started
        </dt>

        <dd>
            @if (Model.TournamentStarted == true)
            {
                <p>Yes</p>
            }
            else
            {
                <p>No</p>
            }
        </dd>

    </dl>
</div>
<hr />
<h4>Teams</h4>
<table>
    @foreach (var team in Model.Teams)
    {
        <tr>
            <td class="col-lg-2">
                @team.TeamName
            </td>
            <td class="col-lg-1">
                @if (Model.TournamentStarted == false)
                {
                @Html.ActionLink("Delete", "Delete", "Team", new { id = team.TeamID }, null)
                }

            </td>
            <td class="col-lg-9"></td>
        </tr>

    }
</table>

<!--if tournament.tournamentstarted = false-->
    @if (Model.TournamentStarted == false)
    {
        <p></p>
        <p>@Html.ActionLink("Add a Team", "Create", "Team", new { TeamTournamentID = Model.TournamentID }, null)</p>
    }
    else
    {
        <p></p>
        <p>Unable to add teams after the tournament has started</p>
    }

<hr />

    @if (Model.TournamentStarted == false)
    {
        <p>@Html.ActionLink("Start Tournament", "RoundRobin", "Tournament", new { id = Model.TournamentID }, null)</p>
    }
    else
    {
        <p>@Html.ActionLink("View Tournament", "RoundRobin", "Tournament", new { id = Model.TournamentID }, null)</p>
    }

<hr />
<p>
    @Html.ActionLink("View all Tournaments", "Index")
</p>

TournamentScheduler/Views/Tournament/Index.cshtml
@model IEnumerable<TournamentScheduler.Models.Tournament>

@{
    ViewBag.Title = "All Tournaments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Tournaments</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TournamentName)
        </th>
        <th>
            Start Date
        </th>
        <th>
            Started
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TournamentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @if (item.TournamentStarted == true)
            {
                <p>Yes</p>
            }
            else
            {
                <p>No</p>
            }
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.TournamentID })
        </td>
    </tr>
}

</table>

TournamentScheduler/Views/Tournament/RoundRobin.cshtml
@model TournamentScheduler.Models.Tournament

@{
    ViewBag.Title = "Round Robin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Round Robin: @Model.TournamentName</h2>
<br />
<h4>Team Scores</h4>
<br />
<table>
    <tr>
        <th class="col-lg-2">
            Team
        </th>
        <th class="col-lg-1">
            Score
        </th>
        <th class="col-lg-9"></th>
    </tr>

    @foreach (var team in Model.Teams)
    {
    <tr>
        <td class="col-lg-2">
            @team.TeamName
        </td>
        <td class="col-lg-1">
            @{
                int scoreCount = 0;
                foreach (var fixture in Model.RRFixtures)
                {
                    if (fixture.Team1Name == team.TeamName)
                    {
                        if (fixture.Team1Score == 1)
                        {
                            scoreCount += 1;
                        }
                    }
                    if (fixture.Team2Name == team.TeamName)
                    {
                        if (fixture.Team2Score == 1)
                        {
                            scoreCount += 1;
                        }
                    }
                }
                <p>@scoreCount</p>
            }
        </td>
        <td class="col-lg-9"></td>
    </tr>
    }
</table>
<br />
<h4>Fixtures</h4>
<br />
@{
    int FinalRound = 0;
    foreach (var fixture in Model.RRFixtures)
    {
        if (fixture.RoundNumber > FinalRound)
        {
            FinalRound = fixture.RoundNumber;
        }
    }
}

@for (var roundCount = 1; roundCount <= FinalRound; roundCount++)
{
    <h4>Round @roundCount</h4>
    <table>
        <tr>
            <th class="col-lg-1">Team 1 Score</th>
            <th class="col-lg-3">Team 1</th>
            <th class="col-lg-1"></th>
            <th class="col-lg-3">Team 2</th>
            <th class="col-lg-1">Team 2 Score</th>
            <th class="col-lg-3"></th>
        </tr>

        @foreach (var fixture in Model.RRFixtures)
        {
            if (roundCount == fixture.RoundNumber)
            {
                if (fixture.Team1Name != null)
                {
                    if (fixture.Team2Name != null)
                    {
                        <tr>
                            <td class="col-lg-1">
                                @fixture.Team1Score
                            </td>
                            <td class="col-lg-3">
                                @fixture.Team1Name
                            </td>
                            <td class="col-lg-1">
                                VS
                            </td>
                            <td class="col-lg-3">
                                @fixture.Team2Name
                            </td>
                            <td class="col-lg-1">
                                @fixture.Team2Score
                            </td>
                            <td class="col-lg-3">
                                <p>@Html.ActionLink("Choose Winner", "Edit", "RRFixture", new { id = fixture.RRFixtureID }, null)</p>
                            </td>
                        </tr>
                    }
                }
            }
        }
    </table>
    <br />
}